config/routes.rb
Engage::Application.routes.draw do

  resources :posts, except: :index do 
     resources :comments, except: [:index]
  end

  resources :profiles, except: :index 
  
  devise_for :users
  
  root :to => 'stream#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :bio, :date_of_birth, :first_name, :job_title, :last_name, :pic_url, :pic_url_medium, :pic_url_thumb
  
  mount_uploader :pic_url, PhotoUploader
   
  belongs_to :user
  belongs_to :account
  


  validates :first_name, :presence => true
  validates :last_name, :presence => true


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
    
    @posts = current_user.posts
    
    #@commentable = @article
    #@comments = @commentable.comments
    #@comment = Comment.new
    
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth, order: [:month, :day] %>
  </div>
  <div class="field">
    <%= f.label :job_title %><br />
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio, :rows => 10 %>
  </div>
  
  <div>
  	<%= f.file_field :pic_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Date of birth</th>
    <th>Job title</th>
    <th>Bio</th>
    <th>Pic url</th>
    <th>Pic url thumb</th>
    <th>Pic url medium</th>
    <th>User</th>
    <th>Account</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.first_name %></td>
    <td><%= profile.last_name %></td>
    <td><%= profile.date_of_birth %></td>
    <td><%= profile.job_title %></td>
    <td><%= profile.bio %></td>
    <td><%= profile.pic_url %></td>
    <td><%= profile.pic_url_thumb %></td>
    <td><%= profile.pic_url_medium %></td>
    <td><%= profile.user %></td>
    <td><%= profile.account %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<div>
	<%= image_tag @profile.pic_url.url(:thumb).to_s, alt: "#{@profile.first_name} #{@profile.last_name}", class: "profile-avatar"  %>
	
</div>
<p>
  <%= @profile.first_name %>
  <%= @profile.last_name %>
</p>

<p>
  <%= @profile.date_of_birth %>
</p>

<p>
  <%= @profile.job_title %>
</p>

<p>
  <%= @profile.bio %>
</p>
<% if current_user.id == @profile.user_id #This method should moved to controller or model %>
	<%= link_to 'Edit', edit_profile_path(@profile) %>
<% end %>



<h1>Listing posts</h1>


<ul class="posts" id="feed">
<% @posts.each do |post| %>
	<li class="post">
		<div class="post-meta">
			<%= link_to(timeago_tag(post.created_at, :nojs => false, :limit => 10.days.ago), post ) %>
		</div>

		<div class="post-content">
			<%= post.content %>
		</div>
		<div class="post-actions">
			<% if current_user.id == post.user_id #This method should moved to controller or model %>
			<ul>
				<li><%= link_to 'Edit', edit_post_path(post) %></li>
				<li><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>			</li>			   	
			</ul>
			<% end %>
		
		</div>
	</li>
<% end %>
</ul>