config/routes.rb
Engage::Application.routes.draw do

  resources :posts, except: :index do 
     resources :comments, except: [:index]
  end

  resources :profiles, except: :index 
  
  devise_for :users
  
  root :to => 'stream#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :commentable_id, :commentable_type, :content, :user_id

  belongs_to :user
  belongs_to :account
  belongs_to :commentable, :polymorphic => true
  
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_filter :load_commentable
  
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  def new
    @comment = @commentable.comments.new
    @comment.user_id = current_user.id
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    
    @comment = @commentable.comments.new(params[:comment])
    if @comment.save
      redirect_to @commentable, notice: "Comment created."
    else
      render :new
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
  
  private

    def load_commentable
      resource, id = request.path.split('/')[1, 2]
      @commentable = resource.singularize.classify.constantize.find(id)
    end
    
end

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 3 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_list.html.erb
<div id="comments">
<% @comments.each do |comment| %>

	<div class="comment-meta">
		<%= timeago_tag(comment.created_at, :nojs => false, :limit => 10.days.ago) %>
	</div>
	<div class="comment-content">
    	<%= simple_format comment.content %>
	</div>
	<div class="comment-action">
		<ul>
			<li><%= link_to 'Edit', edit_post_comment_path(comment) %></li>
			<li><%= link_to 'Delete', post_comment_path(comment), method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %></li>			   	
		</ul>
	</div>
<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<div id="comments">
<% @comments.each do |comment| %>
  <div class="comment">
    <%= simple_format comment.content %>
  </div>
<% end %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>Commentable:</b>
  <%= @comment.commentable_id %>
</p>

<p>
  <b>Commentable type:</b>
  <%= @comment.commentable_type %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user %>
</p>

<p>
  <b>Account:</b>
  <%= @comment.account %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>