config/routes.rb
Engage::Application.routes.draw do

  resources :posts, except: :index do 
     resources :comments, except: [:index]
  end

  resources :profiles, except: :index 
  
  devise_for :users
  
  root :to => 'stream#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :account
  attr_accessible :content
  has_many :comments, :as => :commentable
  
  
  validates :content, :presence => true
  
  before_save do
    self.content.strip! unless self.content.nil?
  end

  after_save do
    self.touch
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  
  
  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.all.reverse
    
    @posts = current_user.posts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_url, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { redirect_to root_url }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to root_url, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  



end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 3 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>


<ul class="posts" id="feed">
<% @posts.each do |post| %>
	<li class="post">
		<div class="post-meta">
			<%= link_to(timeago_tag(post.created_at, :nojs => false, :limit => 10.days.ago), post ) %>
		</div>

		<div class="post-content">
			<%= post.content %>
		</div>
		<div class="post-actions">
			<% if current_user.id == post.user_id #This method should moved to controller or model %>
			<ul>
				<li><%= link_to 'Edit', edit_post_path(post) %></li>
				<li><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>			</li>			   	
			</ul>
			<% end %>
		
		</div>
	</li>
<% end %>
</ul>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="post" id="post">
	<div class="post-meta">
		<%= link_to(timeago_tag(@post.created_at, :nojs => false, :limit => 10.days.ago), post_path(@post) ) %>
		
	</div>

	<div class="post-content">
		<%= @post.content %>
	</div>
	<div class="post-actions">
		
		<% if current_user.id == @post.user_id #This method should moved to controller or model %>
		<ul>
			<li><%= link_to 'Edit', edit_post_path(@post) %></li>
			<li><%= link_to 'Destroy', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>			</li>			   	
		</ul>
		<% end %>
	
	</div>
	
	
	<div class="post-reply" id="name">
		
		<%= render "comments/list" %>		
		<%= render "comments/form" %>
	</div>
</div>